# Generated by Django 3.1 on 2022-10-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('whatsapp', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
