# Generated by Django 3.1 on 2022-10-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_register_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
